# Generated by Django 6.1.1 on 2026-10-02 12:32

import django.db.models.deletion
import memorials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('maiden_name', models.CharField(blank=True, help_text='Affiché « née … »', max_length=100, verbose_name='nom de naissance')),
                ('slug', models.SlugField(blank=True, help_text='Générée automatiquement si laissée vide.', max_length=160, unique=True, verbose_name='adresse de la page')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('death_date', models.DateField(verbose_name='date de décès')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='commune')),
                ('photo', models.ImageField(blank=True, upload_to='avis/%Y/', verbose_name='photo')),
                ('announcement', models.TextField(help_text='Texte de l’avis de décès, tel qu’il apparaîtra sur la page.', verbose_name='texte de l’avis')),
                ('ceremony', models.TextField(blank=True, help_text='Date, heure et lieu des obsèques, de l’inhumation ou de la crémation.', verbose_name='cérémonie')),
                ('family_emails', models.CharField(blank=True, help_text='Reçoivent les messages privés. Plusieurs adresses séparées par des virgules.', max_length=500, validators=[memorials.models.validate_email_list], verbose_name='e-mails de la famille')),
                ('is_published', models.BooleanField(default=False, help_text='Décochez pour masquer la page au public.', verbose_name='publié')),
                ('comments_open', models.BooleanField(default=True, verbose_name='messages autorisés')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'avis de décès',
                'verbose_name_plural': 'avis de décès',
                'ordering': ['-death_date', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='nom')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='message')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Privé (famille uniquement)')], max_length=10, verbose_name='visibilité')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Publié'), ('rejected', 'Refusé'), ('sent', 'Transmis à la famille'), ('failed', 'Échec de l’envoi')], max_length=10, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='memorials.memorial', verbose_name='avis')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
